server:
  port: 8081

spring:
  application:
    name: EstateConnect
    frontend:
      url: http://localhost:5173
  datasource:
    url: jdbc:postgresql://localhost:5432/estate_connect
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      activate-client-token:
        expiration: 86400000 # a day
      activate-agency-token:
        expiration: 86400000 # a day
      reset-password-token:
        expiration: 3600000 # 1 hour
      change-email-token:
        expiration: 3600000 # 1 hour
      change-password-token:
        expiration: 3600000 # 1 hour

file:
  storage:
    location: C:/Users/Owner-PC/Desktop/EstateConnect-master/backend/images

google:
  api:
    key: ${GOOGLE_API_KEY}
