server:
  port: 8081

spring:
  application:
    name: EstateConnect
    frontend:
      url: http://localhost:5174
  datasource:
    url: jdbc:postgresql://localhost:5432/estate_connect
    username: postgres
    password: Donadona576
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: applearnsql@gmail.com
    password: mskmqsnsomyzficg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      activate-client-token:
        expiration: 86400000 # a day
      activate-agency-token:
        expiration: 86400000 # a day
      reset-password-token:
        expiration: 3600000 # 1 hour
      change-email-token:
        expiration: 3600000 # 1 hour
      change-password-token:
        expiration: 3600000 # 1 hour

file:
  storage:
    location: C:/Users/Owner-PC/Desktop/EstateConnect-master/backend/images

google:
  api:
    key: AIzaSyBKcHF5mO7aaNyhmY7iU4H2Te023IeEpSQ